### ISSUE TITLE
Failed to allocate mempool memory, name fe_1

### ISSUE THREAD

**Issue by williamtu** [edmundselliot/doca-selective-fwd#6]
Crash on doca2.8, it used to work ok

Run-time dependency doca-common found: YES 2.8.0082
Run-time dependency libdpdk found: YES 22.11.2407.1.0

```bash
root@doca-vr-061:~/doca/doca-selective-fwd# ./build/doca-selective-fwd -a 12:00.0,dv_flow_en=2 -a 12:00.1,dv_flow_en=2 -c 0x3
[00:33:20:629130][50884][DOCA][INF][main.cpp:158][main] Starting the sample
EAL: Detected CPU lcores: 48
EAL: Detected NUMA nodes: 2
EAL: Detected shared linkage of DPDK
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'VA'
EAL: VFIO support initialized
EAL: Probe PCI driver: mlx5_pci (15b3:a2dc) device: 0000:12:00.0 (socket 0)
EAL: Probe PCI driver: mlx5_pci (15b3:a2dc) device: 0000:12:00.1 (socket 0)
TELEMETRY: No legacy callbacks, legacy socket not created
[00:33:20:680432][50884][DOCA][INF][dpdk_utils.c:472][port_init] Ingress traffic on port 0 is in isolated mode
mlx5_net: port 0 cannot enable promiscuous mode in flow isolation mode
[00:33:21:284230][50884][DOCA][INF][dpdk_utils.c:472][port_init] Ingress traffic on port 1 is in isolated mode
mlx5_net: port 1 cannot enable promiscuous mode in flow isolation mode
mlx5_net: port 0 cannot enable promiscuous mode in flow isolation mode
mlx5_net: port 1 cannot enable promiscuous mode in flow isolation mode
mlx5_common: Failed to unregister mempool fe_1_0_0 for PD 0x5775ee539ba0: No such file or directory
mlx5_common: Failed to unregister mempool fe_1_0_0 for PD 0x5775ee53ca20: No such file or directory
[00:33:26:183589][50884][DOCA][ERR][hws_mempool.c:120][hws_mempool_create] Failed to allocate mempool memory, name fe_1
[00:33:26:183607][50884][DOCA][ERR][engine_pipe.c:577][engine_pipe_create] failed creating pipe - build failed rc=(-12)
[00:33:26:183630][50884][DOCA][ERR][doca_flow.c:1818][doca_flow_pipe_create] engine pipe creation failed, rc = -12
[00:33:26:183644][50884][DOCA][ERR][pipes.cpp:212][create_hairpin_pipe] Failed to create pipe: Memory allocation failure
[00:33:26:183651][50884][DOCA][ERR][pipes.cpp:312][configure_static_pipes] Failed to create hairpin pipe: Memory allocation failure
[00:33:26:217647][50884][DOCA][ERR][main.cpp:98][run_app] Failed to configure static pipes: Memory allocation failure
[00:33:26:217659][50884][DOCA][WRN][engine_port.c:991][engine_port_stop] Port with driver id 1 already stopped
[00:33:26:217665][50884][DOCA][ERR][engine_pipe.c:833][engine_pipe_destroy] failed destroying pipe - pipe is null
[00:33:26:217673][50884][DOCA][ERR][engine_pipe.c:833][engine_pipe_destroy] failed destroying pipe - pipe is null
Segmentation fault (core dumped)
```

gdb

```

Thread 1 "doca-selective-" received signal SIGSEGV, Segmentation fault.
0x00007ffff3045abf in ?? () from /opt/mellanox/doca/lib/x86_64-linux-gnu/libdoca_flow.so.2
(gdb) bt
#0  0x00007ffff3045abf in ?? () from /opt/mellanox/doca/lib/x86_64-linux-gnu/libdoca_flow.so.2
#1  0x00007ffff3019031 in doca_flow_port_stop () from /opt/mellanox/doca/lib/x86_64-linux-gnu/libdoca_flow.so.2
#2  0x000055555555de31 in stop_doca_flow_ports (nb_ports=2, ports=0x7fffffffdaa0) at ../src/flow_common.cpp:250
#3  0x00005555555594ff in run_app (app_cfg=0x7fffffffdb30) at ../src/main.cpp:116
#4  0x000055555555977b in main (argc=7, argv=0x7fffffffde78) at ../src/main.cpp:180
```

**Comment by williamtu** [comment]
fix by
```
echo '10240' | sudo tee -a /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
```
